version: "3.9"

services:
  # ------------------------- PostgreSQL ----------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: claims_postgres
    ports:
      - "5204:5432"                # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin     # matches server.js
      POSTGRES_DB: claims_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks: [claims_net]

  # ------------------------- Node.js API ---------------------------------
  backend:
    build: ./Backend               # uses Backend/Dockerfile
    container_name: claims_backend
    ports:
      - "3204:3204"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin
      PGHOST: postgres
      PGDATABASE: claims_db
      PGPORT: 5432
    networks: [claims_net]

  # ------------------------- Employee portal -----------------------------
  employee-claims:
    build: ./Employee-claims       # uses Employee-claims/Dockerfile
    container_name: employee_claims_ui
    ports:
      - "8008:80"                  # host 8111 → nginx 80
    depends_on:
      - backend
    networks: [claims_net]

  # ------------------------- HR portal -----------------------------------
  hr-claims:
    build: ./HR-claims             # uses HR-claims/Dockerfile
    container_name: hr_claims_ui
    ports:
      - "8009:80"                  # host 8112 → nginx 80
    depends_on:
      - backend
    networks: [claims_net]

volumes:
  pgdata:

networks:
  claims_net:

